name: teamkhagrachari
description: "this is a khagrachari seba app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.0+765

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_widget_from_html_core: ^0.14.11
  lecle_flutter_carousel_pro: ^0.0.3
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  get: ^4.6.6
  intl: any
  share_plus: any
  flutter_local_notifications: ^17.2.1+2
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  http_parser: ^4.0.0
  image:
  permission_handler: ^10.2.0
  in_app_update: ^4.2.3
  device_info_plus: ^11.2.0
  font_awesome_flutter:

  unique_identifier:
  vpn_connection_detector: ^1.0.9
  get_radio_version_plugin: ^1.0.0
  package_info_plus:
  google_mobile_ads: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
     - Assets/images/


  fonts:
     - family: banglafont
       fonts:
         - asset: assets/fonts/bangla.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
